# Default TES instances
tes_uris:
  - "http://131.152.229.70/ga4gh/tes/v1/"
  - "http://193.166.24.111/ga4gh/tes/v1/"

# Default DRS instances
drs_uris:
  - "http://131.152.229.71/ga4gh/drs/v1/"
  - "http://193.166.24.114/ga4gh/drs/v1/"

# Default resources:
resource_requirements:
  cpu_cores: 1
  ram_gb: 1
  disk_gb: 1
  execution_time_min: 30

# Default input files:
drs_ids:
  - "a001"
  - "a002"

# Default mode:
mode: 0.5
