os:
  - linux
dist: bionic
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

if: type != pull_request  # do not build anything for PRs

install:
  - pip install -e .

script:
  - mypy TEStribute setup.py --ignore-missing-imports
  - flake8 TEStribute setup.py
  - pytest --disable-warnings
  - coverage run --source TEStribute -m pytest
  - coveralls

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.8"

