openapi: "3.0.0"
info:
  version: 0.0.1
  title: TEStribute OpenAPI specification
  contact:
    name: 'Elixir Europe'
    email: 'alexander.kanitz@alumni.ethz.ch'
  license:
    name: Apache 2.0
    url: 'https://github.com/elixir-europe/TEStribute/blob/dev/LICENSE'
paths:
  /rank_services:
    post:
      summary: |-
        Returns a rank-ordered list of GA4GH TES and DRS services
        to use when submitting a TES task to decrease total costs and or
        time.
      operationId: RankServices
      requestBody:
        description: |-
          GA4GH TES and DRS services as well as resource
          requirements of the task and the mode (or weight)
          to cost/time to be given
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rankServicesRequirements'
      responses:
        '200':
          description: |-
            On a successful ranking of provided inputs a ranked list
            of TES services with DRS services correspond to the
            object_ids of the required DRS inputs/outputs are returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rankServicesResponse'

components:
  schemas:
    rankServicesRequirements:
      type: object
      properties:
        drs_ids:
          $ref: '#/components/schemas/drsIds'
        drs_uris:
          $ref: '#/components/schemas/drsUris'
        mode:
          anyOf:
            - type: integer
            - type: string
            - type: number
        resource_requirements:
          $ref: '#/components/schemas/resourceRequirements'
        tes_uris:
          $ref: '#/components/schemas/tesUris'
    drsIds:
      type: array
      items:
        type: string
    drsUris:
      type: array
      items:
        type: string
    resourceRequirements:
      type: object
      properties:
        cpu_cores:
          type: integer
        execution_time_min:
          type: integer
          format: int64
        preemptible:
          type: boolean
        ram_gb:
          type: number
        disk_gb:
          type: integer
          format: int64
        zones:
          type: array
          items:
            type: string
    tesUris:
      type: array
      items:
        type: string
    rankServicesResponse:
      type: object
      properties:
        rank:
          type: integer
        tes_drs_combination:
          $ref: '#/components/schemas/tesDrsCombinations'
    tesDrsCombinations:
      type: object
      additionalProperties:
          $ref: '#/components/schemas/objIdDrsCombinations'
    objIdDrsCombinations:
      type: object
      properties:
        object_id:
          additionalProperties:
            type: string
      example:
        "obj_id": "drs_uri"
